# Generated by Django 4.2.1 on 2023-05-30 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisasinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzsakymas',
            name='order_number',
        ),
        migrations.DeleteModel(
            name='UzsakymoEilute',
        ),
    ]
