# Generated by Django 4.2.1 on 2023-05-30 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisasinfo', '0003_uzsakymoeilute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uzsakymoeilute',
            options={'ordering': ['paslauga'], 'verbose_name': 'uzsakymoEilute', 'verbose_name_plural': 'uzsakymoEilutes'},
        ),
    ]
