# Generated by Django 4.2.1 on 2023-05-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisasinfo', '0004_alter_uzsakymoeilute_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobiliomodelis',
            options={'verbose_name': 'automobilio Modelis', 'verbose_name_plural': 'automobiliu modeliai'},
        ),
        migrations.AlterModelOptions(
            name='automobilis',
            options={'ordering': ['client_name', 'client_surname'], 'verbose_name': 'automobilis', 'verbose_name_plural': 'klientu automobiliai'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymoeilute',
            options={'verbose_name': 'uzsakymo Eilute', 'verbose_name_plural': 'uzsakymo Eilutes'},
        ),
        migrations.AddField(
            model_name='uzsakymas',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('0', 'Confirmed'), ('1', 'In Progress'), ('2', 'Finished'), ('3', 'Canceled')], db_index=True, default=0, max_length=1),
        ),
    ]
