# Generated by Django 4.2.1 on 2023-05-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisasinfo', '0005_alter_automobiliomodelis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('0', 'Confirmed'), ('1', 'In Progress'), ('2', 'Finished'), ('3', 'Canceled')], db_index=True, default=0, verbose_name='status'),
        ),
    ]
