# Generated by Django 4.2.1 on 2023-06-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisasinfo', '0007_alter_uzsakymas_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobiliomodelis',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='autoservisasinfo/cars_images', verbose_name='car_image'),
        ),
    ]
