# Generated by Django 4.2.1 on 2023-06-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisasinfo', '0008_automobiliomodelis_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobiliomodelis',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='autoservisas/cars_images', verbose_name='car_image'),
        ),
    ]
