# Generated by Django 4.2.1 on 2023-06-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisasinfo', '0010_automobilis_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobilis',
            options={'ordering': ['user'], 'verbose_name': 'automobilis', 'verbose_name_plural': 'klientu automobiliai'},
        ),
        migrations.RemoveField(
            model_name='automobilis',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='automobilis',
            name='client_surname',
        ),
    ]
