# Generated by Django 4.2.1 on 2023-06-07 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoservisasinfo', '0013_ordercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercomment',
            name='commentator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_comments', to=settings.AUTH_USER_MODEL, verbose_name='Commentator'),
        ),
    ]
