# Generated by Django 4.2.1 on 2023-06-07 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoservisasinfo', '0014_alter_ordercomment_commentator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercomment',
            options={'ordering': ['-commented_at'], 'verbose_name': 'order comment', 'verbose_name_plural': 'order comments'},
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='commentator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_comments', to=settings.AUTH_USER_MODEL, verbose_name='commentator'),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='autoservisasinfo.uzsakymas', verbose_name='order'),
        ),
    ]
