# Generated by Django 4.2.1 on 2023-06-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisasinfo', '0015_alter_ordercomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='price',
            field=models.FloatField(default=0, verbose_name='price'),
        ),
    ]
